[#43] Source updated and merged from change of rageworx/fltk-origin#34

diff --git a/documentation/Makefile b/documentation/Makefile
--- a/documentation/Makefile
+++ b/documentation/Makefile
@@ -55,6 +55,17 @@ MANPAGES =	$(SRC_DOCDIR)/fltk.$(CAT3EXT) $(SRC_DOCDIR)/fltk-config.$(CAT1EXT) \
 		$(SRC_DOCDIR)/checkers.$(CAT6EXT) $(SRC_DOCDIR)/sudoku.$(CAT6EXT) \
 		$(SRC_DOCDIR)/fltk-options.$(CAT1EXT)
 
+# Get FLTK's Git Revision either from Git /or/ from fltk_git_rev.dat (Issue #499)
+#
+# Note: this may fail (return "unknown") if the sources were downloaded
+# from GitHub as a "release" (zip) archive. This is not supported.
+
+# Test/debug only: should be commented out unless used (see: debug_git_rev)
+# GIT_REV_FROM_GIT  := "$$(git rev-parse HEAD 2>/dev/null)"
+# GIT_REV_FROM_FILE := "$$(cat ../fltk_git_rev.dat 2>/dev/null)"
+
+FLTK_GIT_REVISION := "`( (git rev-parse HEAD || cat ../fltk_git_rev.dat;) || echo 'unknown'; ) 2>/dev/null`"
+
 all:	$(MANPAGES)
 
 # Use `make docs' to create all docs for distribution files.
@@ -66,6 +77,11 @@ docs:	all html pdf
 
 alldocs: docs
 dist:	docs
+
+debug_git_rev:
+	# echo "GIT_REV_FROM_GIT  = $(GIT_REV_FROM_GIT)"
+	# echo "GIT_REV_FROM_FILE = $(GIT_REV_FROM_FILE)"
+	echo "FLTK_GIT_REVISION = $(FLTK_GIT_REVISION)"
 
 clean:
 	$(RM) Doxyfile Doxybook
@@ -79,59 +95,59 @@ depend:
 
 install: $(MANPAGES)
 	echo "Installing documentation files in $(DESTDIR)$(docdir) ..."
-	-$(INSTALL_DIR) $(DESTDIR)$(docdir)
+	-$(INSTALL_DIR) "$(DESTDIR)$(docdir)"
 	if test -f html/index.html ; then \
 	  for file in html/* ; do \
-		$(INSTALL_DATA) $$file $(DESTDIR)$(docdir); \
+		$(INSTALL_DATA) $$file "$(DESTDIR)$(docdir)"; \
 	  done \
 	fi
 	if test -f fltk.pdf ; then \
 	  echo "Installing fltk.pdf in $(DESTDIR)$(docdir) ..."; \
-	  $(INSTALL_DATA) fltk.pdf $(DESTDIR)$(docdir); \
+	  $(INSTALL_DATA) fltk.pdf "$(DESTDIR)$(docdir)"; \
 	fi
 	echo "Installing man pages in $(DESTDIR)$(mandir) ..."
-	-$(INSTALL_DIR) $(DESTDIR)$(mandir)/cat1
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fluid.$(CAT1EXT) $(DESTDIR)$(mandir)/cat1
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-config.$(CAT1EXT) $(DESTDIR)$(mandir)/cat1
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-options.$(CAT1EXT) $(DESTDIR)$(mandir)/cat1
-	-$(INSTALL_DIR) $(DESTDIR)$(mandir)/cat3
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk.$(CAT3EXT) $(DESTDIR)$(mandir)/cat3
-	-$(INSTALL_DIR) $(DESTDIR)$(mandir)/man1
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fluid.man $(DESTDIR)$(mandir)/man1/fluid.1
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-config.man $(DESTDIR)$(mandir)/man1/fltk-config.1
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-options.man $(DESTDIR)$(mandir)/man1/fltk-options.1
-	-$(INSTALL_DIR) $(DESTDIR)$(mandir)/man3
-	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk.man $(DESTDIR)$(mandir)/man3/fltk.3
+	-$(INSTALL_DIR) "$(DESTDIR)$(mandir)/cat1"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fluid.$(CAT1EXT) "$(DESTDIR)$(mandir)/cat1"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-config.$(CAT1EXT) "$(DESTDIR)$(mandir)/cat1"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-options.$(CAT1EXT) "$(DESTDIR)$(mandir)/cat1"
+	-$(INSTALL_DIR) "$(DESTDIR)$(mandir)/cat3"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk.$(CAT3EXT) "$(DESTDIR)$(mandir)/cat3"
+	-$(INSTALL_DIR) "$(DESTDIR)$(mandir)/man1"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fluid.man "$(DESTDIR)$(mandir)/man1/fluid.1"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-config.man "$(DESTDIR)$(mandir)/man1/fltk-config.1"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk-options.man "$(DESTDIR)$(mandir)/man1/fltk-options.1"
+	-$(INSTALL_DIR) "$(DESTDIR)$(mandir)/man3"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/fltk.man "$(DESTDIR)$(mandir)/man3/fltk.3"
 
 install-linux install-osx:
-	-$(INSTALL_DIR) $(DESTDIR)$(mandir)/cat6
-	$(INSTALL_MAN) $(SRC_DOCDIR)/blocks.$(CAT6EXT) $(DESTDIR)$(mandir)/cat6
-	$(INSTALL_MAN) $(SRC_DOCDIR)/checkers.$(CAT6EXT) $(DESTDIR)$(mandir)/cat6
-	$(INSTALL_MAN) $(SRC_DOCDIR)/sudoku.$(CAT6EXT) $(DESTDIR)$(mandir)/cat6
-	-$(INSTALL_DIR) $(DESTDIR)$(mandir)/man6
-	$(INSTALL_MAN) $(SRC_DOCDIR)/blocks.man $(DESTDIR)$(mandir)/man6/blocks.6
-	$(INSTALL_MAN) $(SRC_DOCDIR)/checkers.man $(DESTDIR)$(mandir)/man6/checkers.6
-	$(INSTALL_MAN) $(SRC_DOCDIR)/sudoku.man $(DESTDIR)$(mandir)/man6/sudoku.6
+	-$(INSTALL_DIR) "$(DESTDIR)$(mandir)/cat6"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/blocks.$(CAT6EXT) "$(DESTDIR)$(mandir)/cat6"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/checkers.$(CAT6EXT) "$(DESTDIR)$(mandir)/cat6"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/sudoku.$(CAT6EXT) "$(DESTDIR)$(mandir)/cat6"
+	-$(INSTALL_DIR) "$(DESTDIR)$(mandir)/man6"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/blocks.man "$(DESTDIR)$(mandir)/man6/blocks.6"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/checkers.man "$(DESTDIR)$(mandir)/man6/checkers.6"
+	$(INSTALL_MAN) $(SRC_DOCDIR)/sudoku.man "$(DESTDIR)$(mandir)/man6/sudoku.6"
 
 
 uninstall:
-	$(RMDIR) $(DESTDIR)$(docdir)
-	$(RM) $(DESTDIR)$(mandir)/cat1/fluid.$(CAT1EXT)
-	$(RM) $(DESTDIR)$(mandir)/man1/fluid.1
-	$(RM) $(DESTDIR)$(mandir)/cat1/fltk-config.$(CAT1EXT)
-	$(RM) $(DESTDIR)$(mandir)/man1/fltk-config.1
-	$(RM) $(DESTDIR)$(mandir)/cat1/fltk-options.$(CAT1EXT)
-	$(RM) $(DESTDIR)$(mandir)/man1/fltk-options.1
-	$(RM) $(DESTDIR)$(mandir)/cat3/fltk.$(CAT3EXT)
-	$(RM) $(DESTDIR)$(mandir)/man3/fltk.3
+	$(RMDIR) "$(DESTDIR)$(docdir)"
+	$(RM) "$(DESTDIR)$(mandir)/cat1/fluid.$(CAT1EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/man1/fluid.1"
+	$(RM) "$(DESTDIR)$(mandir)/cat1/fltk-config.$(CAT1EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/man1/fltk-config.1"
+	$(RM) "$(DESTDIR)$(mandir)/cat1/fltk-options.$(CAT1EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/man1/fltk-options.1"
+	$(RM) "$(DESTDIR)$(mandir)/cat3/fltk.$(CAT3EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/man3/fltk.3"
 
 uninstall-linux uninstall-osx:
-	$(RM) $(DESTDIR)$(mandir)/cat6/blocks.$(CAT6EXT)
-	$(RM) $(DESTDIR)$(mandir)/cat6/checkers.$(CAT6EXT)
-	$(RM) $(DESTDIR)$(mandir)/cat6/sudoku.$(CAT6EXT)
-	$(RM) $(DESTDIR)$(mandir)/man6/blocks.6
-	$(RM) $(DESTDIR)$(mandir)/man6/checkers.6
-	$(RM) $(DESTDIR)$(mandir)/man6/sudoku.6
+	$(RM) "$(DESTDIR)$(mandir)/cat6/blocks.$(CAT6EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/cat6/checkers.$(CAT6EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/cat6/sudoku.$(CAT6EXT)"
+	$(RM) "$(DESTDIR)$(mandir)/man6/blocks.6"
+	$(RM) "$(DESTDIR)$(mandir)/man6/checkers.6"
+	$(RM) "$(DESTDIR)$(mandir)/man6/sudoku.6"
 
 # The documentation is generated using doxygen. There are two control files
 # for doxygen: Doxyfile for html documentation and Doxybook for pdf docs.
@@ -203,8 +219,7 @@ refman.pdf: $(HTMLFILES) Doxybook src/fltk-book.tex
 
 src/fltk-title.tex: src/fltk-title.tex.in
 	echo "Generating $@ ..."
-	GIT_REVISION=`git rev-parse --short=10 HEAD`; \
-	sed -e"s/@GIT_REVISION@/$$GIT_REVISION/g" \
+	sed -e"s/@FLTK_GIT_REVISION@/$(FLTK_GIT_REVISION)/g" \
 	    < $< > $@
 
 src/fltk-book.tex.in: src/fltk-title.tex
@@ -223,10 +238,9 @@ src/fltk-book.tex: src/fltk-book.tex.in
 generated.dox: generated.dox.in
 	echo "Generating $@ ..."
 	CURRENT_DATE=`date "+%b %d, %Y"`; \
-	GIT_REVISION=`git rev-parse --short=10 HEAD`; \
 	DOXYGEN_VERSION_SHORT=`"$(DOXYDOC)" --version|cut -f1 -d' '`; \
 	sed -e"s/@CURRENT_DATE@/$$CURRENT_DATE/g" \
-	    -e"s/@GIT_REVISION@/$$GIT_REVISION/g" \
+	    -e"s/@FLTK_GIT_REVISION@/$(FLTK_GIT_REVISION)/g" \
 	    -e"s/@DOXYGEN_VERSION_SHORT@/$$DOXYGEN_VERSION_SHORT/g" \
 	    < $< > $@
 
